name: ACEseqWorkflow
channels:
- bioconda
- conda-forge
- defaults
- r
# Packages are lost from some conda channels. To rebuild the environment from scratch you'd need
# a local conda channel with those packages.
- ~/local-conda-channel/
dependencies:
- bioconductor-annotationdbi=1.38.0=r3.3.2_0
- bioconductor-annotationhub=2.6.0=r3.3.2_0
- bioconductor-aroma.light=3.4.0=r3.3.2_0
- bioconductor-biobase=2.34.0=r3.3.2_0
- bioconductor-biocgenerics=0.20.0=r3.3.2_0
- bioconductor-biocinstaller=1.24.0=r3.3.2_0
- bioconductor-biocparallel=1.6.6=r3.3.2_1
- bioconductor-biomart=2.28.0=r3.3.2_0
- bioconductor-biostrings=2.42.1=r3.3.2_0
- bioconductor-biovizbase=1.20.0=r3.3.2_0
- bioconductor-bsgenome=1.42.0=r3.3.2_0
- bioconductor-dnacopy=1.48.0=r3.3.2_0
- bioconductor-ensembldb=1.6.2=r3.3.2_0
- bioconductor-genomeinfodb=1.10.3=r3.3.2_0
- bioconductor-genomicalignments=1.10.0=r3.3.2_0
- bioconductor-genomicfeatures=1.26.4=r3.3.2_0
- bioconductor-genomicranges=1.26.4=r3.3.2_0
- bioconductor-ggbio=1.22.0=r3.3.2_0
- bioconductor-graph=1.50.0=r3.3.2_1
- bioconductor-interactivedisplaybase=1.12.0=r3.3.2_0
- bioconductor-iranges=2.8.2=r3.3.2_0
- bioconductor-organismdbi=1.14.1=r3.3.2_0
- bioconductor-rbgl=1.48.1=r3.3.2_1
- bioconductor-rsamtools=1.26.1=r3.3.2_0
- bioconductor-rtracklayer=1.34.2=r3.3.2_1
- bioconductor-s4vectors=0.12.2=r3.3.2_0
- bioconductor-summarizedexperiment=1.4.0=r3.3.2_2
- bioconductor-variantannotation=1.20.3=r3.3.2_0
- bioconductor-xvector=0.14.1=r3.3.2_0
- bioconductor-zlibbioc=1.20.0=r3.3.2_1
- perl-vcftools-vcf=0.797=pl5.22.0_0
- pysam=0.7.7
- r-bh=1.60.0_2=r3.3.2_0
- r-catools=1.17.1=r3.3.2_1
- r-checkmate=1.8.2=r3.3.2_0
- r-data.table=1.10.4=r3.3.2_0
- r-deoptimr=1.0_6=r3.3.2_0
- r-digest=0.6.12=r3.3.2_0
- r-diptest=0.75_7=r3.3.2_0
- r-e1071=1.6_8=r3.3.2_0
- r-flexclust=1.3_4=r3.3.2_0
- r-flexmix=2.3_14=r3.3.2_0
- r-fnn=1.1=r3.3.2_0
- r-fpc=2.1_10=r3.3.2_0
- r-futile.logger=1.4.1=r3.3.2_0
- r-futile.options=1.0.0=r3.3.2_0
- r-future=1.2.0=r3.3.2_0
- r-getopt=1.20.0=r3.3.2_0
- r-ggally=1.3.0=r3.3.2_0
- r-ggplot2=2.2.1=r3.3.2_0
- r-globals=0.7.1=r3.3.2_0
- r-htmlwidgets=0.5=r3.3.2_0
- r-kernlab=0.9_25=r3.3.2_0
- r-knitr=1.12.3=r3.3.2_0
- r-ks=1.10.5=r3.3.2_0
- r-lambda.r=1.1.7=r3.3.2_0
- r-listenv=0.6.0=r3.3.2_0
- r-matrixstats=0.51.0=r3.3.2_1
- r-mclust=5.2=r3.3.2_0
- r-misc3d=0.8_4=r3.3.2_1
- r-multicool=0.1_10=r3.3.2_0
- r-prabclus=2.2_6=r3.3.2_0
- r-prettyunits=1.0.2=r3.3.2_0
- r-progress=1.0.2=r3.3.2_0
- r-pscbs=0.61.0=r3.3.2_0
- r-r.cache=0.12.0=r3.3.2_0
- r-reshape=0.8.6=r3.3.2_0
- r-scales=0.4.1=r3.3.2_1
- r-snow=0.4_1=r3.3.2_0
- r-tibble=1.2=r3.3.2_1
- r-trimcluster=0.1_2=r3.3.2_0
- r-viridis=0.3.1=r3.3.2_0
- r-yaml=2.1.13=r3.3.2_1
- samtools=0.1.19=2
- tabix=0.2.5=0
- vcftools=0.1.10=0
- bzip2=1.0.6=1
#- cairo # was 1.14.6=4
- certifi=2017.4.17=py27_0
#- fontconfig # was 2.12.1=4
#- freetype # was 2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- graphite2=1.3.9=0
- gsl=2.1=2
#- harfbuzz=1 # was =1.4.3=0
- icu=58.1=1
- jpeg=9b=0
- krb5=1.14.2=0
- libffi=3.2.1=3
- libglu=9.0.0=0
- libiconv=1.14=4
- libpng=1.6.28=1
- libssh2=1.8.0=1
- libtiff=4.0.6=7
- libxml2=2.9.4=4
- ncurses=5.9=10
#- pango=1 # was =1.40.4=0
- pcre=8.39=0
- perl=5.22.0.1=0
- pip=9.0.1=py27_0
- pixman=0.34.0=0
- r-acepack=1.4.1=r3.3.2_0
- r-assertthat=0.1=r3.3.2_0
- r-backports=1.0.5=r3.3.2_0
- r-base=3.3.2=5
- r-base64enc=0.1_3=r3.3.2_0
- r-bitops=1.0_6=r3.3.2_0
- r-class=7.3_14=r3.3.2_0
- r-cluster=2.0.6=r3.3.2_0
- r-codetools=0.2_15=r3.3.2_0
- r-colorspace=1.3_2=r3.3.2_0
- r-curl=2.4=r3.3.2_0
- r-dbi=0.6_1=r3.3.2_0
- r-dichromat=2.0_0=r3.3.2_0
- r-evaluate=0.10=r3.3.2_0
- r-flux=0.3_0=r3.3.2_0
- r-foreign=0.8_67=r3.3.2_0
- r-formatr=1.4=r3.3.2_0
- r-formula=1.2_1=r3.3.2_0
- r-gridextra=2.2.1=r3.3.2_0
- r-gtable=0.2.0=r3.3.2_0
- r-highr=0.6=r3.3.2_0
- r-hmisc=4.0_3=r3.3.2_0
- r-htmltable=1.9=r3.3.2_0
- r-htmltools=0.3.6=r3.3.2_0
- r-httpuv=1.3.3=r3.3.2_0
- r-httr=1.2.1=r3.3.2_0
- r-jsonlite=1.4=r3.3.2_0
- r-kernsmooth=2.23_15=r3.3.2_0
- r-labeling=0.3=r3.3.2_0
- r-lattice=0.20_34=r3.3.2_0
- r-latticeextra=0.6_28=r3.3.2_0
- r-lazyeval=0.2.0=r3.3.2_0
- r-magrittr=1.5=r3.3.2_0
- r-markdown=0.8=r3.3.2_0
- r-mass=7.3_45=r3.3.2_0
- r-matrix=1.2_7.1=r3.3.2_0
- r-memoise=1.1.0=r3.3.2_0
- r-mime=0.5=r3.3.2_0
- r-modeltools=0.2_21=r3.3.2_0
- r-munsell=0.4.3=r3.3.2_0
- r-mvtnorm=1.0_6=r3.3.2_0
- r-nnet=7.3_12=r3.3.2_0
- r-openssl=0.9.6=r3.3.2_0
- r-plogr=0.1_1=r3.3.2_0
- r-plyr=1.8.4=r3.3.2_0
- r-r.methodss3=1.7.1=r3.3.2_0
- r-r.oo=1.21.0=r3.3.2_0
- r-r.utils=2.5.0=r3.3.2_0
- r-r6=2.2.0=r3.3.2_0
- r-rcolorbrewer=1.1_2=r3.3.2_0
- r-rcpp=0.12.10=r3.3.2_0
- r-rcurl=1.95_4.8=r3.3.2_0
- r-reshape2=1.4.2=r3.3.2_0
- r-rgl=0.98.1=r3.3.2_0
- r-robustbase=0.92_7=r3.3.2_0
- r-rpart=4.1_10=r3.3.2_0
- r-rsqlite=1.1_2=r3.3.2_0
- r-shiny=1.0.3=r3.3.2_0
- r-sourcetools=0.1.6=r3.3.2_0
- r-stringi=1.1.2=r3.3.2_0
- r-stringr=1.1.0=r3.3.2_0
- r-survival=2.40_1=r3.3.2_0
- r-xml=3.98_1.6=r3.3.2_0
- r-xtable=1.8_2=r3.3.2_0
- readline #=6.2=0
- setuptools #=36.2.0
- sqlite # upgraded from 3.8.4.1
- tk=8.5.19=1
- wheel=0.29.0
- xz=5.2.2=0
- zlib=1.2.8=3
- curl
- libgcc #=5.2.0=0
- openssl
- python=2 # upgraded from 2.7.9
- system # =5.8=2
- pip
- bx-python=0.7.3
- six=1.10.0
- pkgconfig
- ncephes=1.0.37
- build-capi
- cython=0.24
- numpy #=1.11.3
- numpy-sugar # upgraded from ==1.0.41
- beagle=5.1
- pip:
  - alabaster==0.7.10
  - appdirs==1.4.3
  - asciitree==0.3.3
  - Babel==2.5.1
  - backports.csv==1.0.1
  - backports.ssl-match-hostname==3.4.0.2
  - biopython==1.57
  - brent-search==1.0.18
  - cachetools==2.0.0
  - cloudpickle==0.2.2
  - cobra==0.5.4
  - colorama==0.3.7
  - conda==4.3.16
  - cutadapt==1.13
  - dask==0.14.3
  - docopt==0.6.2
  - docutils==0.14
  - ecdsa==0.13
  - elasticsearch==2.3.0
  - enum34==1.1.6
  - ete2==2.3.10
  - flufl.lock==2.4.1
  - funcsigs==0.4
  - functools32==3.2.3.post1
  - future==0.15.2
  - GPy==0.6.0
  - HTSeq==0.6.1
  - imagesize==0.7.1
  - ipython==3.1.0
  - iterpipes==0.4
  - iterutils==0.1.6
  - Jinja2==2.7.3
  - joblib==0.9.3
  - jsonschema==2.5.1
  - limix-legacy==0.8.12
  - locket==0.2.0
  - MarkupSafe==0.23
  - mistune==0.5.1
  - matplotlib==1.5.3 # was 1.4.3
  - mock==1.3.0
#  - MOFA==0.1
  - ndarray-listener==1.0.20
  - netCDF4==1.2.6
  - nose==1.3.7
  - numexpr==2.6.1
  - optimix==1.2.10
  - packaging==16.8
  - panama==0.58
  - pandas==0.16.2
  - pandas-plink==1.1.7
  - parabam==1.4
  - paramiko==1.16.0
  - partd==0.3.8
  - patsy==0.4.1
  - pbr==1.6.0
  - pip==9.0.1
  - ply==3.10
  - psutil==3.1.1
  - ptyprocess==0.5
  - pybedtools==0.6.2
  - pycosat==0.6.1
  - pycparser==2.14
  - pycrypto==2.6.1
  - Pygments==2.0.2
  - pygp==1.1.10
  - pymongo==3.2.2
  - Pyomo==5.1.1
  - pyparsing==2.0.3
  - PyPDF2==1.26.0
  - pysam==0.7.7
  - pysftp==0.2.8
  - pytabix==0.1
  - python-dateutil==2.4.2
  - pytz==2015.4
  - PyUtilib==5.4.1
  - PyVCF==0.0.0
  - PyYAML==3.11
  - pyzmq==14.6.0
  - radical.utils==0.40
  - requests==2.9.1
  - ruamel.ordereddict==0.4.9
  - ruamel.yaml==0.14.12
  - scikit-learn==0.16.1
  - scipy==0.12.0
  - scipy-sugar==1.0.2
  - setuptools==35.0.2
  - sklearn==0.0
  - snowballstemmer==1.2.1
  - Sphinx==1.6.5
  - sphinxcontrib-websupport==1.0.1
  - toolz==0.8.2
  - tqdm==4.11.2
  - typing==3.6.2
  - urllib3==1.15.1
  - virtualenv==15.1.0
  - xopen==0.1.1
