#!/usr/bin/env bash

export BGZIP_BINARY="bgzip-tabix-$HTSLIB_VERSION"
export TABIX_BINARY="tabix-$HTSLIB_VERSION"
export PERL_BINARY="perl-$PERL_VERSION"
export PYTHON_BINARY="python-$PYTHON_VERSION"
export RSCRIPT_BINARY="Rscript-$RSCRIPT_VERSION"
export INTERSECTBED_BINARY="intersectBed-$BEDTOOLS_VERSION"
export BCFTOOLS_BINARY="bcftools-$SAMTOOLS_VERSION"
export VCFTOOLS_SORT_BINARY="vcf-sort-$VCFTOOLS_VERSION"
export SAMTOOLS_BINARY="samtools-$SAMTOOLS_VERSION"
